### PR TITLE
New feature: Open from editor with the selected table

### PR DESCRIPTION
**Pull request by hjvdwijk**
Hi,

SqlDataInspector is a very nice add on for Azure Data Studio. It is very useful for ETL and data modelling as it easily provides information on the data and on the transformed data in views. There are some features that could be an further improvement. I have some ideas that I would like to work on. As a first step, the dependencies have been updated and a small feature has been added. The header now shows the server name, which is helpful to see what OTAP server is being looked at.

I have quit some experience in developing applications. However, not very recently and although I have worked with HTML, CSS and JavaScript, some developments are new to me. Could you have a look at the changes, if these are correct? And maybe also  make some comments if there are some improvements to be made to style or coding? 

Thank you

### CODE REVIEW

**Comment by hjvdwijk** [comment]
When coding SQL it is nice to quickly open the data inspector on the tables that are used in SQL code. 

Data Inspector now allows the selection of a fully qualified table name (database.schema.table) in the editor and open inspector

screen-071

**Comment by ernstc** [comment]
Hi @hjvdwijk, thank you for the pull request. Very appreciated.

**Comment by ernstc** [comment]
Created issue #17 for tracking the features proposed in thei PR.

**Comment by ernstc** [comment]
Hi @hjvdwijk, I'm reviewing your code and I like the proposed features. There is a regression in the values ordering. I have already fixed it. I have also changed the activation from the selected text in the editor for supporting also notations like "schema.name" or just "name".
I am going to merge your pull request and track the additional changes on the issue #17 .

**Pull request merged**
